import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script';
import MusicPlayerBar from "@/components/MusicPlayerBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Soundbase",
  icons: {
    icon: [
      { url: '/favicon-for-public/web-app-manifest-512x512.png'}
    ]
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white min-h-screen`}
      >
        {children}
        <Script src="https://sdk.scdn.co/spotify-player.js" strategy="afterInteractive" />
        <div className="mt-10">
          <MusicPlayerBar />
        </div>
      </body>
    </html>
  );
}
